language: node_js
node_js:
  - "0.12"

env:
  global:
    - GH_REF=github.com/developmentseed/india-lights.git
    - DEPLOY_BRANCH=master
    - secure: "lyd+5+Gylb3GlIGOYZ4iMYNnyfQHvmYhA0gXH8HpErmh/0NCjE3+dhDY0bGCoErHAzxaDWmmLJ5KZPKfCERD8pXbICL1tne/Ii5qgmcrkN7ufR0IVbFZIkLWUuZEpw6EhOoadj18RG4BASCFfYRkT5TsQGv+ZQd2xp9k5LKn1dyyjLEK2GvA5NC7wwX+4c9QIY6LkLXJ125Rx+JlR3H+Q31kcXOhbiT4jcYskEFKLDwNTjKNpMWiFTxvcj2idd/nNYAqBuTr5IoIBIYg7A+PoTRPMPG1Uo7d9XODvQJzDp5A4BafrEsdkACblHS1g25eM6POWs2tOqGOVy6tt+HLcSFVd1FSZICCkaaydmTv+FCX/ncLjbeKwlnfKIvMNxJcvueEBPbuYM2jWMQ5uP15MiS4TwPjUqkNkM99oFoK3SJQhe9kIMVcSi/1E8cFGIgF+Z0aZuXm2FEJueW77MDKwKv34vCBHTQe1bYWxOHGUFMNxHZHigWDqBt5wlqnc6nEX+xEleOmpdkLPasgRnVEbEDJ8IG6q0Laosb3zWqgRsvHpMZvRq6skvXfnJJHwj2w5gbjoYDDDpFHRCmcfGdMkPl+sXzjvb6aXBGedywwqZlE20ZHV7q2CHzp5mBjzV70YuTxyActJ4fdnxsOzCLstpAOe/rRnkBxzWJ5jxBbC+8="

cache:
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh || true
- npm test

script:
- npm run build

after_success:
- ./.build_scripts/deploy.sh
